from flask import Blueprint, jsonify

canvas_auth = Blueprint("canvas_auth", __name__, url_prefix="/auth/canvas")


@canvas_auth.route("/", methods=["POST"])
def login():
    # TODO: Accept Canvas API token from request body
    #   - Canvas uses personal access tokens (generated by user in Canvas settings)
    #   - Alternatively, Canvas supports OAuth2 if we register as a developer key
    # TODO: Validate the token by making a test request to the Canvas API
    # TODO: Store the Canvas token associated with the user in the database
    return jsonify({"message": "canvas login not implemented"}), 501


@canvas_auth.route("/callback")
def callback():
    # TODO: If using Canvas OAuth2 instead of personal access tokens:
    #   - Receive authorization code from Canvas
    #   - Exchange code for access token
    #   - Store token in database linked to user
    return jsonify({"message": "canvas oauth callback not implemented"}), 501
