import type { Update } from "./types";

export const mockUpdates: Update[] = [
  // Announcements
  {
    id: "1",
    source: "canvas",
    category: "announcement",
    title: "CSE 110 - Midterm Grades Posted",
    snippet:
      "Midterm grades have been posted to Canvas. The class average was 78%. Please review your submission and attend office hours if you have questions.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    url: "https://canvas.ucsd.edu/courses/cse110/announcements/1",
    unread: true,
    priority: "normal",
    course: "CSE 110",
  },
  {
    id: "2",
    source: "email",
    category: "announcement",
    title: "Office Hours Rescheduled - Prof. Johnson",
    snippet:
      "Hi all, due to a department meeting, my office hours this Thursday have been moved from 2-4 PM to 3-5 PM. Please plan accordingly.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    url: "mailto:prof.johnson@ucsd.edu",
    unread: true,
    priority: "normal",
    course: "CSE 101",
  },
  {
    id: "3",
    source: "piazza",
    category: "announcement",
    title: "Instructor Note: Homework 5 Clarification",
    snippet:
      "Good question! For problem 3, you should assume the input array is already sorted. This was clarified in the assignment description.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    url: "https://piazza.com/class/ucsd_cse101/post/567",
    unread: false,
    priority: "normal",
    course: "CSE 101",
  },
  {
    id: "4",
    source: "canvas",
    category: "announcement",
    title: "New Module Available: Week 8 Content",
    snippet:
      "Week 8 lecture slides, readings, and practice problems are now available. Make sure to review before Wednesday's class.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    url: "https://canvas.ucsd.edu/courses/math20c/modules",
    unread: false,
    priority: "normal",
    course: "MATH 20C",
  },
  {
    id: "5",
    source: "email",
    category: "announcement",
    title: "Career Fair Registration Open",
    snippet:
      "The Winter Career Fair is next week! Register now to meet with top tech companies including Google, Microsoft, and Amazon.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    url: "mailto:careers@ucsd.edu",
    unread: false,
    priority: "normal",
  },

  // Exams
  {
    id: "6",
    source: "canvas",
    category: "exam",
    title: "CSE 110 Midterm - Tomorrow",
    snippet:
      "Reminder: Midterm exam is tomorrow at 10:00 AM in Center Hall 101. Bring pencil, calculator, and student ID. Covers chapters 1-5.",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    url: "https://canvas.ucsd.edu/courses/cse110/quizzes/midterm",
    unread: true,
    priority: "urgent",
    course: "CSE 110",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 18),
  },
  {
    id: "7",
    source: "canvas",
    category: "exam",
    title: "MATH 20C Quiz 4 Available",
    snippet:
      "Quiz 4 is now available on Canvas. You have until Friday at 11:59 PM to complete it. The quiz covers sections 12.1-12.5.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    url: "https://canvas.ucsd.edu/courses/math20c/quizzes/4",
    unread: true,
    priority: "normal",
    course: "MATH 20C",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 72),
  },
  {
    id: "8",
    source: "canvas",
    category: "exam",
    title: "CSE 101 Final Exam Schedule",
    snippet:
      "The final exam for CSE 101 will be held on March 15th from 8:00-11:00 AM in Center Hall 101. Please bring your student ID.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48),
    url: "https://canvas.ucsd.edu/courses/cse101/pages/final-exam",
    unread: false,
    priority: "urgent",
    course: "CSE 101",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
  },
  {
    id: "9",
    source: "piazza",
    category: "exam",
    title: "Midterm Review Session - Saturday",
    snippet:
      "TA-led midterm review session this Saturday 2-5 PM in CSE Building Room 1202. Bring your questions!",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
    url: "https://piazza.com/class/ucsd_cse110/post/890",
    unread: true,
    priority: "normal",
    course: "CSE 110",
  },

  // Assignments
  {
    id: "10",
    source: "canvas",
    category: "assignment",
    title: "CSE 110 - Assignment 3 Due Tomorrow",
    snippet:
      "Reminder: Your software engineering group project milestone is due tomorrow at 11:59 PM. Make sure to submit your GitHub repository link and documentation.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    url: "https://canvas.ucsd.edu/courses/cse110/assignments/3",
    unread: true,
    priority: "urgent",
    course: "CSE 110",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24),
  },
  {
    id: "11",
    source: "canvas",
    category: "assignment",
    title: "CSE 101 - Programming Assignment 5",
    snippet:
      "PA5 has been released. Implement a graph algorithm using BFS and DFS. Due in 2 weeks. Start early!",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    url: "https://canvas.ucsd.edu/courses/cse101/assignments/5",
    unread: true,
    priority: "normal",
    course: "CSE 101",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
  },
  {
    id: "12",
    source: "canvas",
    category: "assignment",
    title: "MATH 20C - WebAssign Homework 7",
    snippet:
      "Homework 7 is due this Sunday. Covers integration techniques from Chapter 14. 15 problems total.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
    url: "https://canvas.ucsd.edu/courses/math20c/assignments/hw7",
    unread: false,
    priority: "normal",
    course: "MATH 20C",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4),
  },
  {
    id: "13",
    source: "piazza",
    category: "assignment",
    title: "@mention: Question about Assignment 3",
    snippet:
      "Hey! I saw your question about the assignment. For the API endpoint, you should use POST not GET. Check the spec on page 3.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    url: "https://piazza.com/class/ucsd_cse110/post/234",
    unread: true,
    priority: "normal",
    course: "CSE 110",
  },
  {
    id: "14",
    source: "canvas",
    category: "assignment",
    title: "CSE 30 - Lab 6 Submission",
    snippet:
      "Lab 6 on Assembly Language is due Friday. Make sure to test your code on the ieng6 servers before submitting.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    url: "https://canvas.ucsd.edu/courses/cse30/assignments/lab6",
    unread: false,
    priority: "normal",
    course: "CSE 30",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
  },

  // Events
  {
    id: "15",
    source: "email",
    category: "event",
    title: "Study Group Tonight - Geisel Library",
    snippet:
      "Hey! We're meeting at Geisel Library 2nd floor at 7 PM to study for the algorithms exam. Let me know if you can make it!",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
    url: "mailto:studygroup@ucsd.edu",
    unread: true,
    priority: "normal",
  },
  {
    id: "16",
    source: "piazza",
    category: "event",
    title: "Lab Partner Request",
    snippet:
      "Hi! I noticed you're also looking for a lab partner for CSE 30. Would you like to team up? I've completed most of the prereqs.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    url: "https://piazza.com/class/ucsd_cse30/post/89",
    unread: true,
    priority: "normal",
    course: "CSE 30",
  },
  {
    id: "17",
    source: "email",
    category: "event",
    title: "ACM Meeting - Tech Talk on AI",
    snippet:
      "Join us this Thursday for a tech talk on AI/ML careers with a Google engineer. Pizza provided! CSE Building 1202, 6 PM.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    url: "mailto:acm@ucsd.edu",
    unread: false,
    priority: "normal",
  },
  {
    id: "18",
    source: "email",
    category: "event",
    title: "Winter Career Fair - Next Week",
    snippet:
      "Don't forget to register for the Winter Career Fair! Over 100 companies attending. Price Center West Ballroom, Feb 5th.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36),
    url: "mailto:careers@ucsd.edu",
    unread: false,
    priority: "normal",
  },
  {
    id: "19",
    source: "canvas",
    category: "event",
    title: "CSE 110 Office Hours - Extra Session",
    snippet:
      "Extra office hours this week before the midterm. Wednesday 4-6 PM in CSE Building 3rd floor.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    url: "https://canvas.ucsd.edu/courses/cse110/pages/office-hours",
    unread: true,
    priority: "normal",
    course: "CSE 110",
  },
];

export const quickStats = {
  upcomingDeadlines: 5,
  unreadEmails: 3,
  piazzaMentions: 2,
};
